kind: pipeline
name: build-master-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: jlelse/maily-form
      tags: linux-amd64
    when:
      event:
      - push

trigger:
  ref:
  - refs/heads/master

---
kind: pipeline
name: manifest-master

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  pull: always
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    ignore_missing: true
    spec: manifest.tmpl

trigger:
  ref:
  - refs/heads/master

depends_on:
- build-master-amd64

---
kind: pipeline
name: build-develop-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: jlelse/maily-form
      tags: develop-linux-amd64
    when:
      event:
      - push

trigger:
  ref:
  - refs/heads/develop

---
kind: pipeline
name: manifest-develop

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  pull: always
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    ignore_missing: true
    spec: manifest-develop.tmpl

trigger:
  ref:
  - refs/heads/develop

depends_on:
- build-develop-amd64

---
kind: pipeline
name: build-pull-request

platform:
  os: linux
  arch: amd64

steps:
  - name: dryrun
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: jlelse/maily-form
      tags: pr-linux-amd64
      dry_run: true
    when:
      event:
      - pull_request

trigger:
  ref:
  - "refs/pull/**"
