sudo: required

services:
  - docker

env:
  global:
    - IMAGE_NAME=jlelse/maily-form

language: node_js
node_js:
  - "node"
  - "10"
  - "9"
  - "8"

script:
  - npm test

before_deploy:
  - docker --version
  - docker build -t "$IMAGE_NAME" .
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest"
  on:
    branch: master
