sudo: false

services:
  - docker

env:
  global:
    - IMAGE_NAME=jlelse/maily-form

script:
  - docker --version
  - docker build -t "$IMAGE_NAME" .

before_deploy:
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest"
  on:
    branch: master
