version: 2
jobs:
  build-master:
    docker:
      - image: docker:18.06.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Build latest
          command: docker build -f Dockerfile -t jlelse/maily-form:latest .
      - deploy:
          name: Push latest to DockerHub
          command: |
            echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
            docker push jlelse/maily-form:latest
  build-develop:
    docker:
      - image: docker:18.06.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Build develop
          command: docker build -f Dockerfile -t jlelse/maily-form:develop .
      - deploy:
          name: Push develop to DockerHub
          command: |
            echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
            docker push jlelse/maily-form:develop
  build:
    docker:
      - image: docker:18.06.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Build Docker normal image
          command: docker build -f Dockerfile .
workflows:
  version: 2
  build:
    jobs:
      - build-master:
          filters:
            branches:
              only:
                - master
      - build-develop:
          filters:
            branches:
              only:
                - develop
      - build:
          filters:
            branches:
              ignore:
                - master
                - develop
